version: "3.1"

services:
  postgres:
    build: ./postgres-robots
    image: postgres-robots
    restart: always
    ports:
        - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  pgadmin:
    image: index.docker.io/dpage/pgadmin4
    restart: always
    ports:
      - 8080:8080
    environment:
      PGADMIN_DEFAULT_EMAIL: root@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 8080
    volumes:
      - ./servers.json:/pgadmin4/servers.json:z,ro
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data:
