version: "3.1"

services:

  postgres:
    build: ./postgres-robots
    image: postgres-robots
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: root@muralovka.ru
      PGADMIN_DEFAULT_PASSWORD: toor
    volumes:
      - ./servers.json:/pgadmin4/servers.json:Z,ro
